[2020-03-26 21:46:09,571] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: upload_s3.extract_mail 2020-01-01T11:40:00+00:00 [queued]>
[2020-03-26 21:46:09,594] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: upload_s3.extract_mail 2020-01-01T11:40:00+00:00 [queued]>
[2020-03-26 21:46:09,594] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-03-26 21:46:09,594] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-03-26 21:46:09,594] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-03-26 21:46:09,611] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): extract_mail> on 2020-01-01T11:40:00+00:00
[2020-03-26 21:46:09,614] {standard_task_runner.py:53} INFO - Started process 38651 to run task
[2020-03-26 21:46:09,757] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: upload_s3.extract_mail 2020-01-01T11:40:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-03-26 21:46:20,284] {taskinstance.py:1128} ERROR - EOF occurred in violation of protocol (_ssl.c:749)
Traceback (most recent call last):
  File "/Users/tranquanghuy/email_analytics_dashoard/email_env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/tranquanghuy/email_analytics_dashoard/email_env/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/tranquanghuy/email_analytics_dashoard/email_env/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/tranquanghuy/email_analytics_dashoard/airflow_dir/dags/upload_to_S3.py", line 109, in extract_email
    M = imaplib.IMAP4_SSL('imap.gmail.com')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1280, in __init__
    IMAP4.__init__(self, host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 197, in __init__
    self.open(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1293, in open
    IMAP4.open(self, host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 294, in open
    self.sock = self._create_socket()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 1285, in _create_socket
    server_hostname=self.host)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:749)
[2020-03-26 21:46:20,308] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=upload_s3, task_id=extract_mail, execution_date=20200101T114000, start_date=20200326T114609, end_date=20200326T114620
[2020-03-26 21:46:24,601] {logging_mixin.py:112} INFO - [2020-03-26 21:46:24,598] {local_task_job.py:103} INFO - Task exited with return code 1
